stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  image: python:latest
  stage: build
  only:
    - develop
    - master
  before_script:
    - apt-get update -qq && apt-get install -y -qq npm
    - npm install --save-dev
  script:
    - python generate.py build
  artifacts:
    paths:
      - build/
    expire_in: 1 hour

staging:
  image: python:latest
  stage: deploy
  only:
    - develop
  script:
    - pip install awscli
    - aws s3 sync --acl public-read --delete --region us-west-2 build/ s3://omna-v2-dev

production:
  image: python:latest
  stage: deploy
  only:
    - v1.2.x
  script:
    - pip install awscli
    - aws s3 sync --acl public-read --delete --region us-west-2 build/ s3://omna-v2-prod
