name: Build & Deploy

on:
  push:
    branches: [ develop, master ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
jobs:
  build-and-deploy:

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2

    - name: Set up NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install Dependencies
      run: npm install --save-dev

    - name: Build to Deploy
      run: npx qx deploy -o compiled/deploy

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install AWS Client
      run: pip install awscli

    - name: Deploy in Development
      if: github.ref == 'refs/heads/develop'
      run: aws s3 sync --acl public-read --delete --region us-west-2 compiled/deploy/ s3://omna-v2-dev

    - name: Deploy in Production
      if: github.ref == 'refs/heads/master'
      run: aws s3 sync --acl public-read --delete --region us-west-2 compiled/deploy/ s3://omna-v2-prod
